### ISSUE TITLE
Simplify checkmate() method

### ISSUE THREAD

**Issue by ngjunsiang** [yoyongxuan/ChessGame#22]
## Issue

The [`checkmate()` method](https://github.com/yoyongxuan/ChessGame/blob/cc35818a79c64e1f72df047b68eeac1532fa63ba/chess.py#L328) carries out a number of steps:

1. Determine if king is in check
2. Determine if king is checkmated
3. If checkmated, display the board
4. If checkmated, update the `winner` attribute

Having a single method perform multiple unrelated functions complicates the code in ways that make it harder to maintain:

- There is a redundant call for `check()` which should be split off into `update()`
- The method calls `display()` which is already used in the main game loop, resulting in unnecessary printing
- The game modifies the `winner` attribute, which modifies game behaviour in unpredictable ways if checkmate() needs to be used anywhere else in the code (e.g. in `prompt()`)

## Suggested resolution

1. Split up `checkmate()` into smaller, atomic methods that serve one key purpose.
2. Move the joining code to the main loop, e.g. in `update()`
   - Generally you only need to use `check()` when printing the result of a move (which happens in `update()`), but you may need to use `checkmate()` in `valid_move()` within `prompt()` to determine if a player's move will still result in them being checkmated. Separation of concerns in your code makes it easier to do so.

**Comment by yoyongxuan** [comment]
the reason the method calls the display() method is because the main game loop will break before it displays the board again. Therefore, i called display() again so that players can see the final position of the board when the game ends
